"""Add table BitcoinPrices

Revision ID: 9b5f449d7018
Revises: 
Create Date: 2023-04-28 12:02:10.968829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5f449d7018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitcoin_prices_id'), 'bitcoin_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitcoin_prices_id'), table_name='bitcoin_prices')
    op.drop_table('bitcoin_prices')
    # ### end Alembic commands ###
